language: node_js
node_js:
  - "0.10"
notifications:
  slack:
    on_success: never
    on_failure: never
before_install:
- npm install
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
branches:
only:
- master
script:
- ./node_modules/karma/bin/karma start --single-run
